#!/bin/sh
# Standalone luau has no file I/O, so fixture files are embedded verbatim into
# a generated Luau module that specs can require. Regenerate after adding or
# changing fixtures: `make fixtures` (or `sh scripts/fixtures/embed.sh`).
# examples/ is embedded too (key "examples/<file>") so specs can check it, and
# so are the kube-lens-drift golden diffs (key "tests/shell/drift/cases/<file>")
# that the plugin's diff redaction must agree with.
set -eu

cd "$(dirname "$0")/../.."

out=tests/fixtures/generated.luau
tmp="$out.tmp.$$"
trap 'rm -f "$tmp"' EXIT INT TERM

dirs=""
for d in tests/fixtures/kubectl tests/fixtures/real tests/fixtures/synthetic tests/fixtures/gitops tests/fixtures/drift examples tests/shell/drift/cases; do
	[ -d "$d" ] && dirs="$dirs $d"
done

{
	printf -- '--!strict\n'
	printf -- '-- GENERATED by scripts/fixtures/embed.sh; do not edit. Run `make fixtures`.\n'
	printf 'local files: { [string]: string } = {\n'
	if [ -n "$dirs" ]; then
		# shellcheck disable=SC2086
		find $dirs -type f ! -name 'README.md' ! -name '.*' | LC_ALL=C sort | while IFS= read -r f; do
			key=${f#tests/fixtures/}
			case $key in
			*'"'* | *'\'*)
				echo "embed.sh: unsupported character in fixture path: $f" >&2
				exit 1
				;;
			esac
			# "]=" (not "]=]") so a file ending in "]=" cannot close the string early.
			eq="="
			while grep -qF "]$eq" "$f"; do
				eq="$eq="
			done
			printf '\t["%s"] = [%s[\n' "$key" "$eq"
			cat "$f"
			printf ']%s],\n' "$eq"
		done
	fi
	printf '}\n'
	printf 'return files\n'
} >"$tmp"

mv "$tmp" "$out"
trap - EXIT INT TERM
