#!/usr/bin/env python3
"""Regenerate plugin/lib/kubectl/flags.luau and kinds.luau from a real kubectl.

Usage: KUBECONFIG=.sandbox/kubeconfig python3 scripts/kubectl/gen_tables.py
Flags come from `kubectl options` and `kubectl <cmd> [<sub>] --help` (no cluster
needed); kinds come from `kubectl api-resources` against the disposable kind
cluster. Run `.tools/bin/stylua` on both outputs afterwards.
"""

import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "plugin", "lib", "kubectl")

# pflag NoOptDefVal: bare `--flag` is legal and never consumes the next token.
OPTIONAL = {"dry-run": "unchanged", "validate": "strict", "cascade": "background"}

# Cobra aliases are not printed by --help; verified by running each alias.
ALIASES = {
    "top": {"node": ["nodes", "no"], "pod": ["pods", "po"]},
    "create": {
        "configmap": ["cm"],
        "cronjob": ["cj"],
        "deployment": ["deploy"],
        "ingress": ["ing"],
        "namespace": ["ns"],
        "poddisruptionbudget": ["pdb"],
        "priorityclass": ["pc"],
        "quota": ["resourcequota"],
        "service": ["svc"],
        "serviceaccount": ["sa"],
    },
}


def run(*args):
    return subprocess.run(["kubectl", *args], capture_output=True, text=True, check=True).stdout


def version():
    return run("version", "--client").splitlines()[0].split(":", 1)[1].strip()


def parse_flags(text):
    out = {}
    for line in text.splitlines():
        m = re.match(r"^\s+(?:-(\w), )?--([\w-]+)=(.*?):\s*$", line)
        if m:
            short, name, default = m.groups()
            out[name] = (short, default in ("true", "false"))
    return out


def subcommands(text):
    names = []
    for block in re.split(r"\n(?=\S)", text):
        if "Commands" in block.split("\n")[0]:
            for line in block.splitlines()[1:]:
                m = re.match(r"^  ([a-z][\w-]*)\s", line)
                if m and m.group(1) not in ("help", "completion"):
                    names.append(m.group(1))
    return names


def walk(path, depth, commands, subs):
    text = run(*path, "--help")
    commands[" ".join(path)] = parse_flags(text)
    children = subcommands(text)
    if path and children:
        subs[" ".join(path)] = children
    if depth < 2:
        for child in children:
            walk(path + [child], depth + 1, commands, subs)


def lua_list(items):
    return "{ " + ", ".join(f'"{i}"' for i in items) + " }" if items else "{}"


def flag_spec(flags):
    def enc(name, short):
        return f"{name}/{short}" if short else name

    bools = sorted(enc(n, s) for n, (s, b) in flags.items() if b)
    values = sorted(enc(n, s) for n, (s, b) in flags.items() if not b)
    return f"{{ bool = {lua_list(bools)}, value = {lua_list(values)} }}"


def gen_flags(ver):
    globals_ = parse_flags(run("options"))
    commands, subs = {}, {}
    for top in subcommands(run("--help")):
        walk([top], 1, commands, subs)
    lines = [
        "--!strict",
        f"-- Generated by scripts/kubectl/gen_tables.py from kubectl {ver}",
        "-- (`kubectl options` and `kubectl <cmd> [<sub>] --help`). Do not edit by hand.",
        "-- Entry format: \"long\" or \"long/s\" where s is the shorthand.",
        "",
        "export type FlagSpec = { bool: { string }, value: { string } }",
        "",
        "local M = {}",
        "",
        f"M.kubectlVersion = \"{ver}\"",
        "",
        f"M.global = {flag_spec(globals_)} :: FlagSpec",
        "",
        "M.optionalValue = {",
    ]
    lines += [f'\t["{k}"] = "{v}",' for k, v in sorted(OPTIONAL.items())]
    lines += ["} :: { [string]: string }", "", "M.commands = {"]
    lines += [f'\t["{k}"] = {flag_spec(v)},' for k, v in sorted(commands.items())]
    lines += ["} :: { [string]: FlagSpec }", "", "M.subcommands = {"]
    lines += [f'\t["{k}"] = {lua_list(v)},' for k, v in sorted(subs.items())]
    lines += ["} :: { [string]: { string } }", "", "M.subcommandAliases = {"]
    for parent, table in sorted(ALIASES.items()):
        lines.append(f'\t["{parent}"] = {{')
        for canon, als in sorted(table.items()):
            for a in als:
                lines.append(f'\t\t["{a}"] = "{canon}",')
        lines.append("\t},")
    lines += ["} :: { [string]: { [string]: string } }", "", "return M", ""]
    with open(os.path.join(OUT, "flags.luau"), "w") as fh:
        fh.write("\n".join(lines))


def gen_kinds(ver):
    rows = []
    for line in run("api-resources", "--no-headers").splitlines():
        parts = line.split()
        if len(parts) == 5:
            name, short, gv, ns, kind = parts
        else:
            name, gv, ns, kind = parts
            short = ""
        group = gv.rsplit("/", 1)[0] if "/" in gv else ""
        rows.append((name, short.split(",") if short else [], group, ns == "true", kind))
    lines = [
        "--!strict",
        f"-- Generated by scripts/kubectl/gen_tables.py from `kubectl api-resources` (kubectl {ver})",
        "-- against the disposable kind cluster. Do not edit by hand.",
        "-- Entry format: { plural, kind, group (\"\" = core), namespaced, shortNames }.",
        "-- Order matters: the first entry wins when a name or short name is shared.",
        "",
        "export type Row = { plural: string, kind: string, group: string, namespaced: boolean, short: { string } }",
        "",
        "return {",
    ]
    for name, short, group, ns, kind in rows:
        lines.append(
            f'\t{{ plural = "{name}", kind = "{kind}", group = "{group}", '
            f"namespaced = {str(ns).lower()}, short = {lua_list(short)} }},"
        )
    lines += ["} :: { Row }", ""]
    with open(os.path.join(OUT, "kinds_data.luau"), "w") as fh:
        fh.write("\n".join(lines))


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    v = version()
    gen_flags(v)
    gen_kinds(v)
